// app/layout.tsx or app/layout.js
import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";

import Footer from "@/components/web/Footer";

import Navbar from "@/components/web/Navbar/Navbar";
import { Toaster } from "sonner";
import AuthProvider from "@/components/Provider/AuthProvider";
import Providers from "@/components/Provider/providers";

// Import Raleway font
const raleway = Raleway({
  subsets: ["latin"],
  variable: "--font-raleway",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Seul-Miraz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${raleway.className} scroll-smooth`}>
      <body className={`${raleway.variable} antialiased`}>
        <Providers>
          <AuthProvider>
            <Navbar />
            {children}
            <Toaster position="top-right" />
            <Footer />
          </AuthProvider>
        </Providers>
      </body>
    </html>
  );
}
